# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapOfDangerous' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapOfDangerous

  target 'MapOfDangerousTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapOfDangerousUITests' do
    # Pods for testing
  end
  
  pod "Alamofire"
  pod "SDWebImage"
  pod "SwiftLint"
  pod 'lottie-ios'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'FirebaseFirestoreSwift', '8.3.0-beta'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'IQKeyboardManagerSwift'
  pod 'Google-Maps-iOS-Utils', '~> 3.1.4'
  pod 'SwiftKeychainWrapper', '~> 4.0'
  pod 'MarqueeLabel'

end
